// The end-to-end scenario for the pool: one real shroud and one real unshroud (a partial exit), with every number
// fixed so the proof is reproducible.
//
//   npm run e2e:gen
//
// writes ../circuits/pool/e2e.toml (circuit inputs) and ../contracts/test/fixtures/e2e_scenario.json (the numbers the
// Foundry test reads). Then `circuits/pool/scripts/prove_e2e.sh` makes the proof, and
// contracts/test/OpaquePoolE2E.t.sol runs it through the real pool, hasher and verifier.
import { writeFileSync } from "node:fs";
import { type Note, commitment, extDataHash, noteStub, ownerKey } from "./notes.ts";
import { MerkleTree } from "./tree.ts";
import { buildWitness } from "./witness.ts";

export const SCENARIO = {
  nk: 4242n,
  assetId: 1n,
  // the note Alice shrouds
  rho: 101n,
  r: 202n,
  shroudTokens: 1000n * 10n ** 18n,
  // the first deposit into an empty pool mints tokens * 1e6 shares (the pool's virtual offset)
  shares: 1000n * 10n ** 18n * 1_000_000n,
  // the unshroud: 40% of the shares leave, the rest comes back as a change note
  exitShares: 400n * 10n ** 18n * 1_000_000n,
  changeRho: 303n,
  changeR: 404n,
  spareRho: 505n,
  spareR: 606n,
  dummyRho: 707n,
  dummyR: 808n,
  recipient: "0x00000000000000000000000000000000000b0b00",
  caller: "0x0000000000000000000000000000000000000000",
  relayerFee: 0n,
  ciphertext0: new Uint8Array([0xc0]),
  ciphertext1: new Uint8Array([0xc1]),
};

export function buildScenario() {
  const s = SCENARIO;
  const opk = ownerKey(s.nk);
  const note: Note = { opk, rho: s.rho, r: s.r, assetId: s.assetId, amount: s.shares };

  // what the pool's tree holds after the shroud: one leaf, hash4(1, stub, asset, shares)
  const tree = new MerkleTree();
  const index = tree.insert(commitment(note));

  const ext = {
    recipient: s.recipient,
    caller: s.caller,
    fee: s.relayerFee,
    data: new Uint8Array(),
    ciphertext0: s.ciphertext0,
    ciphertext1: s.ciphertext1,
  };
  const witness = buildWitness({
    tree,
    assetId: s.assetId,
    inputs: [{ nk: s.nk, note, index }],
    outputs: [
      { opk, rho: s.changeRho, r: s.changeR, assetId: s.assetId, amount: s.shares - s.exitShares },
      { opk, rho: s.spareRho, r: s.spareR, assetId: s.assetId, amount: 0n },
    ],
    exitAmount: s.exitShares,
    extDataHash: extDataHash(ext),
    dummy: { rho: s.dummyRho, r: s.dummyR },
  });
  return { note, tree, witness, stub: noteStub(opk, s.rho, s.r) };
}

const h = (v: bigint) => "0x" + v.toString(16);

if (import.meta.url === `file://${process.argv[1]}`) {
  const { witness, stub } = buildScenario();
  const p = witness.publicInputs;
  const s = SCENARIO;
  writeFileSync(new URL("../circuits/pool/e2e.toml", import.meta.url), witness.proverToml);
  writeFileSync(
    new URL("../contracts/test/fixtures/e2e_scenario.json", import.meta.url),
    JSON.stringify(
      {
        note: "Generated by sdk/e2e.ts. Do not edit by hand.",
        stub: h(stub),
        shroudTokens: h(s.shroudTokens),
        shares: h(s.shares),
        exitShares: h(s.exitShares),
        root: h(p.root),
        nullifier0: h(p.nullifier0),
        nullifier1: h(p.nullifier1),
        commitment0: h(p.commitment0),
        commitment1: h(p.commitment1),
        assetId: h(p.assetId),
        exitAmount: h(p.exitAmount),
        extDataHash: h(p.extDataHash),
        recipient: s.recipient,
        caller: s.caller,
        relayerFee: h(s.relayerFee),
        ciphertext0: "0xc0",
        ciphertext1: "0xc1",
      },
      null,
      2,
    ) + "\n",
  );
  console.log("wrote circuits/pool/e2e.toml and contracts/test/fixtures/e2e_scenario.json");
}
