#!/usr/bin/env python3
"""Generate contracts/src/Poseidon2Hasher.sol from Barretenberg's Poseidon2 (BN254, t=4) parameters.

Usage:
    python3 tools/gen_poseidon2.py path/to/poseidon2_params.hpp > contracts/src/Poseidon2Hasher.sol

Source of the constants: aztec-packages, barretenberg/cpp/src/barretenberg/crypto/poseidon2/poseidon2_params.hpp
(tag v1.2.1). Noir's `poseidon2_permutation` builtin and Barretenberg use these same constants, so this hasher
matches `poseidon::poseidon2::Poseidon2::hash` in the circuit. tests check that with vectors taken from Noir.
"""
import re
import sys

src = open(sys.argv[1]).read()

diag_block = src[src.index("internal_matrix_diagonal"):src.index("internal_matrix =")]
diag = re.findall(r'0x[0-9a-fA-F]{64}', diag_block)
assert len(diag) == 4

rc_start = src.index("round_constants{")
rc_block = src[rc_start:]
# the file holds one struct for BN254; take exactly the 64 rounds x 4 constants that follow the marker
rc = re.findall(r'0x[0-9a-fA-F]{64}', rc_block)[:64 * 4]
assert len(rc) == 64 * 4, len(rc)
rc = [rc[i * 4:(i + 1) * 4] for i in range(64)]

P = 21888242871839275222246405745257275088548364400416034343698204186575808495617

out = []
w = out.append
w("// SPDX-License-Identifier: MIT")
w("pragma solidity ^0.8.26;")
w("")
w('import {IHasher} from "./interfaces/IHasher.sol";')
w("")
w("/// @title Poseidon2Hasher")
w("/// @notice Poseidon2 over BN254 (t = 4, d = 5, 8 full + 56 partial rounds), as used by Noir and Barretenberg.")
w("/// @dev GENERATED by tools/gen_poseidon2.py. Do not edit by hand. Matches `poseidon::poseidon2::Poseidon2::hash`.")
w("///      hash2 = sponge over [a, b] with iv = 2 << 64. hash4 = sponge over [a, b, c, d] with iv = 4 << 64.")
w("contract Poseidon2Hasher is IHasher {")
w("    uint256 internal constant P = %d;" % P)
w("    uint256 internal constant TWO_POW_64 = 18446744073709551616;")
w("")
w("    function hash2(uint256 a, uint256 b) external pure returns (uint256) {")
w("        (uint256 r,,,) = _perm(a, b, 0, 2 * TWO_POW_64);")
w("        return r;")
w("    }")
w("")
w("    function hash4(uint256 a, uint256 b, uint256 c, uint256 d) external pure returns (uint256) {")
w("        (uint256 s0, uint256 s1, uint256 s2, uint256 s3) = _perm(a, b, c, 4 * TWO_POW_64);")
w("        (uint256 r,,,) = _perm(addmod(s0, d, P), s1, s2, s3);")
w("        return r;")
w("    }")
w("")
w("    function _perm(uint256 a, uint256 b, uint256 c, uint256 d)")
w("        internal")
w("        pure")
w("        returns (uint256, uint256, uint256, uint256)")
w("    {")
w("        assembly {")
# mds as inline yul statements
mds = """
            // external matrix, in place on (a, b, c, d)
            let t0 := addmod(a, b, p)
            let t1 := addmod(c, d, p)
            let t2 := addmod(addmod(b, b, p), t1, p)
            let t3 := addmod(addmod(d, d, p), t0, p)
            let t4 := addmod(addmod(t1, t1, p), addmod(t1, t1, p), p)
            t4 := addmod(t4, t3, p)
            let t5 := addmod(addmod(t0, t0, p), addmod(t0, t0, p), p)
            t5 := addmod(t5, t2, p)
            a := addmod(t3, t5, p)
            b := t5
            c := addmod(t2, t4, p)
            d := t4
"""
# Yul has no macros, so define the matrix as a function and sbox as a function.
w("            function mds(x0, x1, x2, x3) -> o0, o1, o2, o3 {")
w("                let p := %s" % hex(P))
w("                let t0 := addmod(x0, x1, p)")
w("                let t1 := addmod(x2, x3, p)")
w("                let t2 := addmod(addmod(x1, x1, p), t1, p)")
w("                let t3 := addmod(addmod(x3, x3, p), t0, p)")
w("                let t1x2 := addmod(t1, t1, p)")
w("                let t4 := addmod(addmod(t1x2, t1x2, p), t3, p)")
w("                let t0x2 := addmod(t0, t0, p)")
w("                let t5 := addmod(addmod(t0x2, t0x2, p), t2, p)")
w("                o0 := addmod(t3, t5, p)")
w("                o1 := t5")
w("                o2 := addmod(t2, t4, p)")
w("                o3 := t4")
w("            }")
w("            function sbox(x) -> y {")
w("                let p := %s" % hex(P))
w("                let x2 := mulmod(x, x, p)")
w("                y := mulmod(mulmod(x2, x2, p), x, p)")
w("            }")
w("            function full(x0, x1, x2, x3, k0, k1, k2, k3) -> o0, o1, o2, o3 {")
w("                let p := %s" % hex(P))
w("                o0, o1, o2, o3 := mds(sbox(addmod(x0, k0, p)), sbox(addmod(x1, k1, p)), sbox(addmod(x2, k2, p)), sbox(addmod(x3, k3, p)))")
w("            }")
w("            function partial(x0, x1, x2, x3, k0) -> o0, o1, o2, o3 {")
w("                let p := %s" % hex(P))
w("                x0 := sbox(addmod(x0, k0, p))")
w("                let sum := addmod(addmod(x0, x1, p), addmod(x2, x3, p), p)")
w("                o0 := addmod(mulmod(x0, %s, p), sum, p)" % diag[0])
w("                o1 := addmod(mulmod(x1, %s, p), sum, p)" % diag[1])
w("                o2 := addmod(mulmod(x2, %s, p), sum, p)" % diag[2])
w("                o3 := addmod(mulmod(x3, %s, p), sum, p)" % diag[3])
w("            }")
w("")
w("            a, b, c, d := mds(a, b, c, d)")
for i in range(4):
    w("            a, b, c, d := full(a, b, c, d, %s, %s, %s, %s)" % tuple(rc[i]))
for i in range(4, 60):
    w("            a, b, c, d := partial(a, b, c, d, %s)" % rc[i][0])
for i in range(60, 64):
    w("            a, b, c, d := full(a, b, c, d, %s, %s, %s, %s)" % tuple(rc[i]))
w("        }")
w("        return (a, b, c, d);")
w("    }")
w("}")
print("\n".join(out))
