#!/usr/bin/env python3
"""Generate sdk/poseidon2_constants.ts from contracts/src/Poseidon2Hasher.sol.

The TypeScript hash must use the very same constants as the contract and the circuit, so they are read out of the
generated Solidity file instead of being copied by hand.

Usage:
    python3 tools/gen_poseidon2_ts.py > sdk/poseidon2_constants.ts
"""
import re

src = open("contracts/src/Poseidon2Hasher.sol").read()
full = re.findall(r"a, b, c, d := full\(a, b, c, d, (0x[0-9a-f]{64}), (0x[0-9a-f]{64}), (0x[0-9a-f]{64}), (0x[0-9a-f]{64})\)", src)
part = re.findall(r"a, b, c, d := partial\(a, b, c, d, (0x[0-9a-f]{64})\)", src)
diag = re.findall(r"mulmod\(x[0-3], (0x[0-9a-f]{64}), p\)", src)
assert len(full) == 8 and len(part) == 56 and len(diag) == 4, (len(full), len(part), len(diag))

print("// GENERATED by tools/gen_poseidon2_ts.py from contracts/src/Poseidon2Hasher.sol. Do not edit by hand.")
print("// Poseidon2 over BN254, t = 4: 4 full rounds, 56 partial rounds, 4 full rounds.")
print()
print("export const FULL_ROUND_CONSTANTS: bigint[][] = [")
for row in full:
    print("  [" + ", ".join(c + "n" for c in row) + "],")
print("];")
print()
print("export const PARTIAL_ROUND_CONSTANTS: bigint[] = [")
for c in part:
    print("  " + c + "n,")
print("];")
print()
print("export const INTERNAL_DIAGONAL: bigint[] = [" + ", ".join(c + "n" for c in diag) + "];")
