name: ci

on:
  push:
  pull_request:

jobs:
  contracts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: foundry-rs/foundry-toolchain@v1
      - name: Install forge-std
        run: git clone --depth 1 https://github.com/foundry-rs/forge-std lib/forge-std
      - name: Build
        run: forge build
      - name: Test
        run: forge test -vv

  circuit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: noir-lang/noirup@v0.1.4
        with:
          toolchain: 1.0.0-beta.11
      - name: Test circuit
        working-directory: circuits/pool
        run: nargo test
